module:
  addtoany: 0
  addtocal: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_a11ychecker: 0
  ckeditor_balloonpanel: 0
  config: 0
  config_filter: 0
  config_split: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  email_formatter: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  inline_entity_form: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  node: 0
  node_read_time: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redis: 0
  responsive_image: 0
  responsive_menu: 0
  search: 0
  simple_sitemap: 0
  slick: 0
  slick_paragraphs: 0
  slick_ui: 0
  slick_views: 0
  smart_trim: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  ucpe_common: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
  ucpe_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
